### ISSUE TITLE
Kotlin error running startserver.bat

### ISSUE THREAD

**Issue by SirOMGitsYOU** [BloodyMods/ServerStarter#15]
kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
        at atm.bloodworkxgaming.serverstarter.ForgeManager.startServer(ForgeManager.kt:163)
        at atm.bloodworkxgaming.serverstarter.ForgeManager.handleServer(ForgeManager.kt:42)
        at atm.bloodworkxgaming.serverstarter.ServerStarter.startLoading(ServerStarter.kt:184)
        at atm.bloodworkxgaming.serverstarter.ServerStarterKt.main(ServerStarter.kt:195)

**Comment by HexF** [comment]
As seen in [the source](https://github.com/BloodyMods/ServerStarter/blob/v1.2.7/src/main/kotlin/atm/bloodworkxgaming/serverstarter/ForgeManager.kt), the property  `level-name` is missing from your `server.properties` file. Add this in and it should work.
