### ISSUE TITLE
Missing jansi? on aarch64

### ISSUE THREAD

**Issue by TreeHD** [BloodyMods/ServerStarter#41]
Hello
I was installing modpack
then occur those error

Already check on x86 (java_290),it's working 
but on aarch64 it doesn't working

My Java environment
```
➜  b7f1504f-5d8d-4c9f-a4a6-05a6770eb19f java8 -version 
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)
```
When Run
```
➜  b7f1504f-5d8d-4c9f-a4a6-05a6770eb19f bash startserver.sh
Skipping download. Using existing serverstarter-2.1.0.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.fusesource.jansi.AnsiConsole.ansiStream(AnsiConsole.java:239)
        at org.fusesource.jansi.AnsiConsole.initStreams(AnsiConsole.java:542)
        at org.fusesource.jansi.AnsiConsole.systemInstall(AnsiConsole.java:496)
        at atm.bloodworkxgaming.serverstarter.ServerStarterKt.main(ServerStarter.kt:198)
Caused by: java.lang.RuntimeException: Unable to load jansi native library
        at org.fusesource.jansi.internal.JansiLoader.initialize(JansiLoader.java:62)
        at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:30)
        ... 4 more
Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=aarch64, paths=[/usr/java/packages/lib/aarch64:/lib:/usr/lib]
        at org.fusesource.jansi.internal.JansiLoader.loadJansiNativeLibrary(JansiLoader.java:333)
        at org.fusesource.jansi.internal.JansiLoader.initialize(JansiLoader.java:60)
        ... 5 more
```

**Comment by BloodWorkXGaming** [comment]
Huh, that is indeed an interesting case.. Didn't cosider/have a way to test on aarch64 devices.

Will see if there is a way to remove/disable jansi in that case. Colors will of course be lacking then.

**Comment by BloodWorkXGaming** [comment]
2.3.0 should hopefully fix this, if not, please reopen this issue :)
