### ISSUE TITLE
server not loading

### ISSUE THREAD

**Issue by hribik100** [BloodyMods/ServerStarter#45]
it starts with this fail Failed to create mod instance. (am using atm7 modpack)
```
Failed to create mod instance. ModID: dummmmmmy, class net.mehvahdjukaar.dummmmmmy.DummmmmmyMod
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.17.1-37.0.109.jar%23182!:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.17.1-37.0.109.jar%23181!:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-16-openjdk-amd64/lib/libawt_xawt.so
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2387) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:746) ~[?:?]
	at java.lang.System.load(System.java:1857) ~[?:?]
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169) ~[?:?]
	at jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:310) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:280) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2392) ~[?:?]
	at java.lang.Runtime.loadLibrary0(Runtime.java:808) ~[?:?]
	at java.lang.System.loadLibrary(System.java:1893) ~[?:?]
	at java.awt.Toolkit$2.run(Toolkit.java:1389) ~[?:?]
	at java.awt.Toolkit$2.run(Toolkit.java:1387) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:312) ~[?:?]
	at java.awt.Toolkit.loadLibraries(Toolkit.java:1386) ~[?:?]
	at java.awt.Toolkit.<clinit>(Toolkit.java:1419) ~[?:?]
	at java.awt.Color.<clinit>(Color.java:275) ~[?:?]
	at net.mehvahdjukaar.dummmmmmy.common.Configs.<clinit>(Configs.java:27) ~[MmmMmmMmmMmm-1.17-1.4.1.jar%23114!:1.17-1.4.0]
	at net.mehvahdjukaar.dummmmmmy.DummmmmmyMod.<init>(DummmmmmyMod.java:34) ~[MmmMmmMmmMmm-1.17-1.4.1.jar%23114!:1.17-1.4.0]
	... 14 more
```
and the cyclil fails too
```
Failed to create mod instance. ModID: cyclic, class com.lothrazar.cyclic.ModCyclic
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.17.1-37.0.109.jar%23182!:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.17.1-37.0.109.jar%23181!:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class java.awt.Color
	at com.lothrazar.cyclic.config.ClientConfigCyclic.<clinit>(ClientConfigCyclic.java:13) ~[Cyclic-1.17.1-1.6.2.jar%2369!:1.17.1-1.6.2]
	at com.lothrazar.cyclic.config.ConfigRegistry.initClientConfig(ConfigRegistry.java:318) ~[Cyclic-1.17.1-1.6.2.jar%2369!:1.17.1-1.6.2]
	at com.lothrazar.cyclic.config.ConfigRegistry.initConfig(ConfigRegistry.java:309) ~[Cyclic-1.17.1-1.6.2.jar%2369!:1.17.1-1.6.2]
	at com.lothrazar.cyclic.config.ConfigRegistry.<clinit>(ConfigRegistry.java:99) ~[Cyclic-1.17.1-1.6.2.jar%2369!:1.17.1-1.6.2]
	at com.lothrazar.cyclic.ModCyclic.<init>(ModCyclic.java:31) ~[Cyclic-1.17.1-1.6.2.jar%2369!:1.17.1-1.6.2]
	... 14 more
```
and then server crahses
and then the chash report
```
Crash Report UUID: 12b5aac7-e6b3-4584-9116-c14843a8b344
	FML: 37.0
	Forge: net.minecraftforge:37.0.109[14:22:59] [main/FATAL]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	MmmMmmMmmMmm (dummmmmmy) has failed to load correctly
§7java.lang.reflect.InvocationTargetException: null,
	Cyclic (cyclic) has failed to load correctly
§7java.lang.reflect.InvocationTargetException: null
]
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:236) ~[fmlcore-1.17.1-37.0.109.jar%23181!:?]
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:201) ~[fmlcore-1.17.1-37.0.109.jar%23181!:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[fmlcore-1.17.1-37.0.109.jar%23181!:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:178) ~[fmlcore-1.17.1-37.0.109.jar%23181!:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:178) ~[fmlcore-1.17.1-37.0.109.jar%23181!:?]
	at net.minecraftforge.fmllegacy.server.ServerModLoader.load(ServerModLoader.java:45) ~[forge-1.17.1-37.0.109-universal.jar%23184!:?]
	at net.minecraft.server.Main.main(Main.java:100) ~[server-1.17.1-20210706.113038-srg.jar%23180!:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.17.1-37.0.109.jar%2322!:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]
```
am on ubuntu 20.04 with java 
```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 16.0.1+9-Ubuntu-120.04, mixed mode, sharing)
```

**Comment by hribik100** [comment]
i solved it

**Comment by aldesrahim** [comment]
how did you solved it?

**Comment by JurkoDev** [comment]
Idk it's been 4years and I don't even know what I did to get here also it's with cyclic and create that's 4 years old so I don't think that's the issue you have
