### ISSUE TITLE
Latest API Commit still broken

### ISSUE THREAD

**Issue by itsdinkd** [BloodyMods/ServerStarter#68]
Forked the latest commit to be able to use curseforge API. I have a CFCore API which I entered in the config, however, it looks like its not working - downloading mods.

```java
[13:33:18] [INFO] Requesting Download links from curse api.
GetModFilesRequestBody(fileIds=[3694035, 3834803, 3728163, 3782775, 3864315, 3814476, 3773319, 3689026, 3717999, 3835362, 3824945, 3830510, 3732839, 3846085, 3822990, 3846766, 3570654, 3804386, 3860622, 3693350, 3345570, 3813785, 3679841, 3866408, 3804330, 3545928, 3697655, 3544000, 3671141, 3856670, 3820500, 3830796, 3798505, 3842007, 3837966, 3687422, 3209972, 3683627, 3736161, 3849579, 3671418, 3564781, 3801086, 3671362, 3832920, 3834732, 3834918, 3866659, 3846467, 3840013, 3573395, 3856923, 3669187, 3818011, 3595821, 3856140, 3850251, 3668220, 3843500, 3854317, 3568159, 3852809, 3801919, 3821022, 3667391, 3856355, 3773907, 3602969, 3822975, 3831429, 3756730, 3838648, 3837786, 3816761, 3707430, 3696707, 3791214, 3541670, 3727733, 3550632, 3829226, 3777451, 3859309, 3823445, 3851656, 3783101, 3782788, 3723927, 3770970, 3770564, 3837390, 3814370, 3670317, 3787306, 3765362, 3743933, 3709779, 3764447, 3831347, 3668153, 3659789, 3527187, 3809518, 3679776, 3838886, 3658063, 3814359, 3726288, 3666466, 3788614, 3782801, 3682270, 3778232, 3813616, 3537445, 3606973, 3543360, 3859633, 3790470, 3761198, 3684915, 3718002, 3840291, 3850113, 3840350, 3692220, 3838424, 3785027, 3809741, 3820311, 3871777, 3817474, 3868888, 3806862, 3842099, 3810366, 3833479, 3833892, 3832657, 3668243, 3749858, 3834606, 3765372, 3709672, 3671220, 3667477, 3837204, 3737263, 3740439, 3850090, 3802327, 3772875, 3841646, 3841995, 3728272, 3794897, 3543273, 3682009, 3793676, 3850786, 3764565, 3788444, 3855187, 3695866, 3834418, 3712495, 3779089, 3854539, 3673151, 3757609, 3861266, 3830915, 3851928, 3796516, 3698682, 3847899, 3736226, 3847947, 3809939, 3793306, 3786685, 3667401, 3830795, 3821045, 3612206, 3570678, 3681918, 3661225, 3778759, 3818504, 3864859, 3822757, 3725770, 3725500, 3695179, 3783618, 3841438, 3798366, 3807049, 3818277, 3840513, 3548092, 3845600, 3788678, 3551503, 3793504, 3862523, 3751167, 3854065, 3742064, 3852543, 3822702, 3541792, 3801127, 3802721, 3768225, 3681186, 3785658, 3769487, 3851278, 3723542, 3757529, 3755798, 3870767, 3665605, 3734902, 3779559, 3788081, 3841573, 3825553, 3779101, 3829392, 3738298, 3763996, 3847142, 3808822, 3772638, 3854977, 3770217, 3725895, 3764752, 3826192, 3745661, 3854732, 3807435, 3796954, 3816496, 3759591, 3836838, 3747170, 3614231, 3853797, 3801263, 3764470, 3672601, 3802476, 3821321, 3767285, 3802194, 3846163, 3865454, 3822250, 3833847, 3773641, 3671377, 3790474, 3686895, 3772806, 3710116, 3686478, 3683673, 3856054, 3855243, 3837169, 3767473, 3752361, 3782224, 3817053, 3750059, 3865969, 3820947, 3680863, 3814362, 3710888, 3758381, 3765309, 3764869, 3782712, 3672635, 3821006, 3822522, 3848372, 3786184, 3834227, 3133167, 3555653, 3820231, 3787154, 3764813, 3668091, 3770936, 3793108, 3790158, 3827354, 3668182, 3687750, 3842674, 3847377, 3851061, 3784307, 3783332, 3758296, 3824297, 3830308, 3833878, 3861254, 3781828, 3855172, 3777271, 3754872, 3708158, 3808405, 3855800, 3758209, 3864556, 3751370, 3846805, 3677546, 3829152, 3583880, 3392902, 3830907, 3793698, 3675784, 3752286, 3811283, 3672248, 3795903, 3668284, 3860820, 3778610, 3820867, 3860912, 3734912, 3667807, 3866891, 3797131, 3751441, 3680371, 3836331, 3856246, 3777660, 3855093, 3777836, 3708800, 3851257, 3855404, 3843302, 3769825, 3821194, 3683667, 3695148, 3808156, 3671252, 3740565, 3765424, 3668184, 3798506, 3682488, 3813945, 3556912, 3759595])
[13:33:19] [ERROR] Error while installing pack

java.io.IOException: Request to https://api.curseforge.com/v1/mods/files was not successful. Error Code: 403
        at atm.bloodworkxgaming.serverstarter.packtype.curse.CursePackType.requestModInformation(CursePackType.kt:206)
        at atm.bloodworkxgaming.serverstarter.packtype.curse.CursePackType.downloadMods(CursePackType.kt:243)
        at atm.bloodworkxgaming.serverstarter.packtype.curse.CursePackType.postProcessing(CursePackType.kt:161)
        at atm.bloodworkxgaming.serverstarter.packtype.AbstractZipbasedPackType.installPack(AbstractZipbasedPackType.kt:32)
        at atm.bloodworkxgaming.serverstarter.ServerStarter.startLoading(ServerStarter.kt:165)
        at atm.bloodworkxgaming.serverstarter.ServerStarterKt.main(ServerStarter.kt:214)
[13:33:19] [ERROR] Some uncaught error happened.

java.io.IOException: Request to https://api.curseforge.com/v1/mods/files was not successful. Error Code: 403
        at atm.bloodworkxgaming.serverstarter.packtype.curse.CursePackType.requestModInformation(CursePackType.kt:206)
        at atm.bloodworkxgaming.serverstarter.packtype.curse.CursePackType.downloadMods(CursePackType.kt:243)
        at atm.bloodworkxgaming.serverstarter.packtype.curse.CursePackType.postProcessing(CursePackType.kt:161)
        at atm.bloodworkxgaming.serverstarter.packtype.AbstractZipbasedPackType.installPack(AbstractZipbasedPackType.kt:32)
        at atm.bloodworkxgaming.serverstarter.ServerStarter.startLoading(ServerStarter.kt:165)
        at atm.bloodworkxgaming.serverstarter.ServerStarterKt.main(ServerStarter.kt:214)
[13:33:19] [WARNING] Shutdown Hook called, trying to stop any running subprocess.
```

**Comment by Ocraftyone** [comment]
Yeah. Bloody has not released new version. You can either build the project yourself or I have a repository that already has the Curseforge api implemented.
https://github.com/Ocraftyone/ServerStarter-CFCorePatch

**Comment by itsdinkd** [comment]
> Yeah. Bloody has not released new version. You can either build the project yourself or I have a repository that already has the Curseforge api implemented. https://github.com/Ocraftyone/ServerStarter-CFCorePatch

As I mentioned in the original post, I've forked it using the latest commit and that includes building it. This error is from that

**Comment by Ocraftyone** [comment]
Whoops! My bad!

**Comment by BloodWorkXGaming** [comment]
What api key are you using?

In case you use your own one, that is expected behavior, due to the
disallowed third-party Downloads of some mods.

Still thinking about how to handle those best. One way is to use the
official curse key as a workaround as suggested by some people in the other
issue.

itsdinkd ***@***.***> schrieb am Do., 14. Juli 2022, 22:34:

**Comment by Ocraftyone** [comment]
Yup. Just what Bloody said. If you want to do the hacky work around you can get the official api key from the CF app. Instructions are in the repo I mentioned previously
